# Generated by Django 3.1.7 on 2021-04-02 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=200)),
                ('pricePerMinute', models.PositiveIntegerField()),
                ('timeOpen', models.TimeField()),
                ('timeClose', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('rangeOfSearch', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
