# Generated by Django 3.1.7 on 2021-04-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_ms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Parking_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField()),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation_ms.parking_lot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation_ms.user')),
            ],
        ),
    ]
