# Generated by Django 3.1.7 on 2021-04-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_ms', '0003_auto_20210405_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_parking_lot',
            name='distance_to_destination',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
