version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - .:/app
    depends_on: 
      - db

  db:
    image: mysql:8.0.23
    restart: always
    environment: 
      MYSQL_DATABASE: recommendation_db
      MYSQL_USER: "user_ms"
      MYSQL_PASSWORD: "Password1!"
      MYSQL_ROOT_PASSWORD: "11260224"
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306